# فایل: pubspec.yaml
# تنظیمات پروژه Smart Money Bell

name: smart_money_bell
description: اپلیکیشن هوشمند مدیریت سرمایه‌گذاری و وفاداری مشتریان

# نسخه برنامه
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # فارسی‌سازی
  flutter_localizations:
    sdk: flutter
  
  # آیکون‌های Cupertino
  cupertino_icons: ^1.0.8
  
  # مدیریت state (ضروری برای architecture)
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# تنظیمات Flutter
flutter:
  # فعال‌سازی Material Design
  uses-material-design: true
  
  # منابع (Assets)
  assets:
    - assets/images/
    - assets/icons/
  
  # فونت‌های فارسی
  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazirmatn-Regular.ttf
          weight: 400
        - asset: assets/fonts/Vazirmatn-Bold.ttf  
          weight: 700
    - family: IRANSans
      fonts:
        - asset: assets/fonts/IRANSans-Light.ttf
          weight: 400
        - asset: assets/fonts/IRANSans-Bold.ttf
          weight: 700
  
  # منابع (Assets)
